"""Recraft motif adapter: ``prompt -> normalized motif`` registered at authoring time.

Complex motifs (paisley, florals, …) are generated by an external API (Recraft) rather
than shipped as a hand-built library. The hard rule (ARCHITECTURE.md "결정론"): this is
an **authoring-time** step, never runtime ``generate``. We call the generator once,
normalize + allowlist the result, register it under a stable content-hash ``motif_id``,
and from then on the runtime references the id only — so the same intent + seed always
yields the same SVG.

The generator is an injected seam (a ``Protocol``), mirroring :mod:`app.adapters.llm`:
no SDK is added to ``requirements.txt`` and tests inject a fake client.

Caching is two-layered and both layers preserve determinism:
- a per-prompt cache avoids re-invoking the generator for an identical request;
- the ``motif_id`` is the hash of the *normalized* geometry, so two different prompts
  that normalize to the same shape collide to the same id (a registry cache hit).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from app.adapters.base import AdapterClientError, cache_key
from app.motifs.registry import normalize_motif_svg, register_motif


@runtime_checkable
class RecraftClient(Protocol):
    """Minimal motif-generation seam: a prompt in, a raw SVG string out."""

    def generate(self, prompt: str) -> str: ...


class RecraftError(AdapterClientError):
    """The Recraft generator is unavailable or failed (maps to a 5xx if surfaced)."""


class RecraftNotConfigured(RecraftError):
    """No Recraft client was injected and none is configured as the default."""


def _resolve_client(client: RecraftClient | None) -> RecraftClient:
    if client is None:
        raise RecraftNotConfigured(
            "no Recraft client provided; pass create_motif(client=...). "
            "Generation is opt-in and authoring-time only."
        )
    return client


# Per-prompt cache: prompt -> motif_id, so an identical authoring request never
# re-invokes the generator. Distinct from the content-hash id dedup in the registry.
_motif_cache: dict[str, str] = {}


def clear_motif_cache() -> None:
    _motif_cache.clear()


def create_motif(
    prompt: str,
    *,
    client: RecraftClient | None = None,
    use_cache: bool = True,
) -> str:
    """Generate, normalize, and register a motif at authoring time; return its ``motif_id``.

    Raises :class:`RecraftError` if the generator is unavailable or fails, and
    propagates :class:`app.render.sanitize.SanitizeError` / ``ValueError`` if the
    generated SVG is unsafe or unnormalizable.
    """
    if not prompt or not prompt.strip():
        raise ValueError("create_motif requires a non-empty prompt")
    key = cache_key({"k": "recraft", "prompt": prompt})
    if use_cache and key in _motif_cache:
        return _motif_cache[key]

    generator = _resolve_client(client)
    try:
        raw_svg = generator.generate(prompt)
    except RecraftError:
        raise
    except Exception as exc:  # any generator failure is an upstream (5xx-class) error
        raise RecraftError(f"Recraft generation failed: {exc}") from exc

    motif = normalize_motif_svg(raw_svg)
    motif_id = register_motif(motif)
    if use_cache:
        _motif_cache[key] = motif_id
    return motif_id
